In [1]:
import numpy as np

In [2]:
A= np.array([
    [1, -1, 2],
    [3, 2, 2], 
    [4, 1, 2],
])


In [4]:
A_transpose = np.transpose(A)
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [6]:
A_transpose = A.T
A_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [7]:
# identity matrix
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
A @ i

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [9]:
# 역행렬 구하는 함수
# 역행렬이 없는 경우 역행렬과 최대한 비슷한 행렬 출력
A_inverse = np.linalg.pinv(A)
A_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [10]:
A @ A_inverse

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 2.22044605e-16,  1.00000000e+00, -8.88178420e-16],
       [ 2.22044605e-16,  2.22044605e-16,  1.00000000e+00]])