In [1]:
import numpy as np

In [4]:
# 행렬은 2차원 배열을 사용
A= np.array([
    [1, -1, 2],
    [3, 2, 2], 
    [4, 1, 2],
    [7, 5, 6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [5]:
B = np.array([
    [0,1],
    [-1, 3],
    [5, 2]
])

B

array([[ 0,  1],
       [-1,  3],
       [ 5,  2]])

In [6]:
C = np.random.rand(3,5)

C

array([[0.96048114, 0.0801449 , 0.82588955, 0.39222552, 0.32151152],
       [0.52285476, 0.47128589, 0.15147748, 0.40114023, 0.07544995],
       [0.20218962, 0.04291869, 0.89963153, 0.76416553, 0.85832146]])

In [10]:
D = np.zeros((2,4))

D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [12]:
# 0부터 시작함을 유의
A[0][2]

2

In [13]:
# 벗어나면 오류
A[0][5]

IndexError: index 5 is out of bounds for axis 0 with size 3